[bugfix/enhancement]: Support Navidrome structured lyrics
jeffvli/feishin pull request #484
Opened 2024-02-02 08:03 UTC by kgarner7

This PR provides support for OpenSubsonic structured lyrics (Navidrome >= 0.51.0), and also stores server version/features.

Changes:
- `useServerVersion()`: fetches server version on open, and when changed. This is essential for OS clients to know what features are supported
- `useSongLyricsBySong()`: now supports fetching from OS to retrieve all structured lyrics. If multiple lyrics are shown, a select is available

Notes:
- `offset` is currently not used (of note, it has the opposite meaning to what Feishin does)
- could probably have a better interface for language selection?
- Older versions of Navidrome should still be supported

2024-02-04 04:49 UTC, jeffvli requested changes

2024-02-04 04:49 UTC, jeffvli commented on src/renderer/api/jellyfin/jellyfin-controller.ts
> +        throw new Error('Failed to get song detail');
This error message should be for server info.

2024-02-04 04:49 UTC, jeffvli commented on src/renderer/api/subsonic/subsonic-controller.ts
> +        throw new Error('Failed to get server extensions');
This error message should be for the lyrics.

2024-02-04 04:51 UTC, jeffvli commented on src/renderer/features/lyrics/lyrics.tsx
> +                    )}
This should be moved into the `LyricsActions` component.

2024-02-04 06:51 UTC, kgarner7 commented
Also resolves #311 with newest change

2024-02-14 00:17 UTC, jeffvli approved these changes

2024-02-14 00:17 UTC, merged