[feat]  Create "Add current track" button in playlist view
jeffvli/feishin pull request #560
Opened 2024-03-27 01:54 UTC by will-hut

I'm enjoying using Feishin as my music player for my library. I thought it would be nice to add a "Add current track" button to the playlist sidebar. That way, when a song is playing, I can quickly add it to as many playlists as I feel like it belongs in.

![demo](https://github.com/jeffvli/feishin/assets/22407192/b937be34-08f9-490e-9638-03160900492e)

Currently, I have it hiding the button if the playlist has rules (ie, a smart playlist). You can add a playlist to a shared album, but if you don't have (admin) permission, it throws an error toast. 

This also allows adding duplicates of a song to a playlist, so a toggle somewhere to disable duplicates could be a nice feature.

I'm not a React dev and haven't really contributed to open source, so if there's any issues please let me know! I think I did a decent job, but I'm always looking for ways to make my code better.

2024-03-27 02:13 UTC, will-hut commented
This adds a feature similar to what is mentioned in #556

2024-04-03 01:58 UTC, kgarner7 commented on src/renderer/features/sidebar/components/sidebar-playlist-list.tsx
> +                },
You should move the `toast.success` to `onSuccess` here

2024-04-03 02:18 UTC, kgarner7 requested changes
Thanks for the commit! A few other thoughts:
- This doesn't consider duplicates (e.g. adding the same song multiple times)
- The new icon isn't quite intuitive, maybe it'd be worthwhile to remove the delay for tooltip (or another icon)

I'm also not sure if this is necessarily appropriate period, but I'll defer to @jeffvli for that.

2024-04-03 02:18 UTC, kgarner7 commented on src/renderer/features/sidebar/components/sidebar-playlist-list.tsx
> +            handleAdd: handleAddCurrent,
This should not be enabled for Navidrome shared playlists (only the owner can change them)

2025-06-07 08:07 UTC, closed without merging